export const GLOBAL_CONSTANTS = {
    HOME_NAVLINKS : "Home",
    SERVICES_NAVLINKS : "Services",
    ABOUTUS_NAVLINKS : "About Us",
    HINTUS_NAVLINKS : "Hint Us",
    CONTACT_NAVLINKS : "Contact",
    SIGNIN_NAVLINKS : "Login / Sign Up",
    GETSTARTED : 'Get Started',
    APPVIEWCONTENT : "We create a detailed scope of work",
    OURSERVICES : "Our Services",
    DOCTEXT : "Doctor",
    DOCATHOME : "Doctor At Your Home",
    DOCATHOMECONTENT : "Hint Bharat's Doctor at home service revolutionizes healthcare by bringing expert medical care to the comfort of your own home. This innovative service connects you with a network of experienced & qualified doctors who will visit you at your doorstep, providing personalized medical attention and treatment with doctor at home, you can consult Our doctors for expert care without the hassle of clinic visits. Our doctors carry essential medical equipment for on-site diagnosis & prescription, ensuring Our doctors carry essential medical equipment for on-site diagnosis & prescription, ensuring all age groups ensuring your health concerns are addressed promptly and efficiently.",
    MEDICINE : "Medicine",
    MEDICINECONTENT : "Hint Bharat is transforming the Indian healthcare industry by providing dependable and easy-to-use medication delivery services. The portal makes ordering and getting medications easier by letting users explore a large selection of products, upload prescriptions, and keep track of orders in real time. Genuine, appropriately stored, and prompt delivery are guaranteed by Hint Bharat's partnerships with reliable pharmacies and distributors. Long pharmacy lines can be less stressful thanks to this service, which also provides recurring orders for ongoing medical care. Priorities one and two are safety and privacy, with strict procedures for secure transactions and safe handling. Hint Bharat empowers patients to concentrate on improving their health by becoming a partner in their journey.",
    PATHOLOGY : "Pathology",
    PATHOLOGYCONTENT : "Hint Bharat is redefining healthcare by providing convenient, dependable, and all-inclusive pathology services at home in partnership with top pathology labs around the nation. Without the inconvenience of visiting a clinic, our platform links patients with premier diagnostic labs, guaranteeing precise and fast findings. We provide a comprehensive range of services that may be scheduled at your convenience, from standard blood tests to cutting-edge diagnostics. Our skilled workers take samples directly from your door while upholding the strictest safety and hygienic requirements. Hint Bharat strives to make healthcare more patient-centric, efficient, and accessible by providing a smooth workflow, digital reporting, and choices for professional advice. This will enable people to easily take charge of their health.",
    NURSING : "Nursing",
    NURSINGCONTENT : "Hint Bharat, provides comprehensive nursing services at home, ensuring high-quality care in the comfort of your own space. Through strategic collaborations with esteemed nursing colleges, we bring a team of highly trained, compassionate, and certified nursing professionals right to your doorstep. Whether you need post-operative care, elderly support, chronic disease management, or palliative care, our nurses are equipped with the skills and knowledge to cater to a wide range of healthcare needs. Our mission at Hint Bharat is to provide individualized services that support recuperation, self-sufficiency, and general well-being to close the gap between hospital and home care. We make sure that our staff stays at the forefront of nursing excellence by collaborating closely with the best academic institutions and fusing cutting-edge medical procedures with a patient-centred methodology. You or your loved ones can recover and flourish at home with Hint Bharat's competent, trustworthy, and compassionate nursing care.",
    PHYSIOTHERAPY : "Physiotherapy",
    PHYSIOTHERAPYCONTENT : "Hint Bharat is transforming healthcare by offering excellent physiotherapy services at your door. Our in-home physiotherapy services are intended for people who want individualized care without having to deal with the inconvenience of going to the clinic. Our team of qualified and skilled physiotherapists customizes each treatment plan to match your unique needs, whether you are recovering from surgery, managing chronic pain, or trying to increase mobility. Our mission at Hint Bharat is to assist you in regaining your strength, mobility, and independence via individualized therapy sessions. We recognize that recovery occurs best in the comfort of your own home. Our experts use the latest techniques and equipment to ensure effective treatment for conditions such as post-surgical rehabilitation, arthritis, sports injuries, stroke recovery, and more. Experience professional care at your convenience with Hint Bharat’s trusted physiotherapy services, and let us help you on your path to better health and wellness.",
    DOWNLOADTEXT : "Download Hint App Now!",
    DOWNLOADTEXTCONTENT : "We start the project with an in-depth business analysis to identify and define the requirements that must be fulfilled to achieve the project's objective. We need to know the goals, the problem that we're solving,",
    ABOUTUSCONTENT : "Revolutionizing Healthcare in India: Bridging the Gap with HINT for Doorstep Doctor Visits in Tier 1 and Tier 2 Cities, would be providing our services PAN India soon. India's healthcare system is on the cusp of a transformation, driven by the urgent need to bridge the significant gap between doctors and patients. While advancements in telemedicine have been a step forward, the limitations of virtual consultations have become apparent, particularly when it comes to accurate and diagnosis and treatment....",
    HINTFOOTERTEXT : "©️ Hint 2024.All Rights Reserved Powered by",
    FOOTERTEXT : "Hint.",
    JOINTEXT : "Join our newsletter",
    JOINCONTENT : "We'll send you a nice letter once per week",
    CONPANYTEXT : "Company",
    SOCIALTEXT : "Social",
    POSTQUERY : "Post a query",
    FEEDBACKTEXT : "Give Your Feed Back",
    WRTIETOUS : "Write to us",
    EMAIL : "Email-Hintbharat@gmail.com",
    PHONE : "Phone- 1234567890",
    CONTACTUS : "Contact Us",
    DISCLAIMERTEXT : "Disclaimer",
    REFUND : "Refund",
    PRIVACY : "Privacy",
    TERMS : "Terms",
    LEGAL : "Legal",
    ARTICLES : "Articles",
    EVENTS : "Events",
    NEWSLETTER : "News Letter",
    PATIENTCARE : "Patient Care",
    FAQ : "FAQ",
    WHYCHOOSE : "Why Choose Us ?",
    QUICKLINKS : "QuickLinks",
    TESTIMONIALS : "Testimonials",
    NAME1 : "Akshay Mishra",
    REVIEW1 : 'This idea of providing mobile medical services from palliative, geriative care and support to other crucial medicinal delivery will certainly help people across age and help geographies to ensure healthy life.',
    NAME2 : "Amar Tiwari",
    REVIEW2 : "HINT's doctor-at-home service is going to be so helpful,especially for elderly patients. No more waiting in clinics, justquality care at home.",
    NAME3 : "Amit Pandey",
    REVIEW3 : "Medicine delivery right at your doorstep? That's a fantastic idea! HINT will save us all from those last-minute pharmacy runs, especially when we're unwell. Looking forward to using this service!",
    NAME4 : "Archana Pandey",
    REVIEW4 : "It is an awesome and very much valuable scheme. When I came to know about HINT ,I was spellbound.",
    NAME5 : "Arjun Chaudhary",
    REVIEW5 : "HINT! will undoubtedly bridge the gap between patients and medical professionals, making quality healthcare more convenient a n d efficient. HINT has the potential to positively impact billions of lives in India and abroad. Unlike your app's motto - 'Health In No Time' - success takes time, but your vision and dedication will transform the Indian medical system in no time!",
    NAME6 : "Atul Chaudhary",
    REVIEW6 : "A very unique and must needed idea will definitely bring drastic changes in medical needs for customers in this busy scenario",
    NAME7 : "Chandra Dev Patel",
    REVIEW7 : "HINT's doctor-at-home service is going to be so helpful,especially for elderly patients. No more waiting in clinics, justquality care at home.",
    NAME8 : "Deepanshu Verma",
    REVIEW8 : "It is really a nice idea of doctor visiting the patient's house..as many times patients are not able to visit hospitals due to different reasons.. it becomes more helpful a s it will reduce gatherings in hospitals so chances of spreading diseases also reduces.",
    NAME9 : "Dhirendra Kumar",
    REVIEW9 : "Why always we have to go to doctor, this time doctor will visit at your door step for your health concern without spending too many bucks this will be made possible by the hint. best and innovative idea for this generation.",
    NAME10 : "Geetika Singh",
    REVIEW10 : "The brand has exceeded expectations, providing exceptional medical services. Their commitment to care and satisfaction is genuine. I'm grateful for their service and confident in recommending them.",
    NAME11 : "Jitendra Sengar",
    REVIEW11 : "HINT's doctor-at-home service is going to make healthcare more comfortable and convenient for people who struggle with traveling to clinics. I'm excited to see how it works!",
    NAME12 : "Pooja Verma",
    REVIEW12 : "HINT's doctor-at-home service is going to be so helpful,especially for elderly patients. No more waiting in clinics, justquality care at home.",
    NAME13 : "Rishi Nag",
    REVIEW13 : "This is such a great idea for patients. Home visit doctors provide care at home to patients who are unable to travel long distances to a doctor's clinic or hospital. They act like a medical concierge and treat the patient in the comfort of their home. Elderly patients cannot stand in line to get an appointment at a hospital and hence prefer to get treated at home by the doctor.",
    NAME14 : "Sangram Singh",
    REVIEW14 : "I love the idea of HINT's doctor-at-home service. It's perfect for families with kids and elderly people. No more dragging them to the hospital for every appointment!",
    NAME15 : "Shaurya Yadav",
    REVIEW15 : "Idea of this  website fascinated means a lot ! It helped m e in saving time and getting best consultation in a short duration of time ! Also best for older aged group!",
};